[package]
name = "nocargo"
version = "0.0.0"
edition = "2018"
license = "MIT"
description = "WIP: reserved"
repository = "https://github.com/oxalica/nocargo"

[dependencies]
anyhow = "1.0.40"
structopt = "0.3.21"
